### ISSUE TITLE
Search characters being filtered

### ISSUE THREAD

**Issue by Steve-A-Orr** [quist00/onesearch-local#15]
This is observed by one of the librarians here at Fresno State:

> If you use the search box on our home page, it seems that punctuation and/or "special" characters get left out of your search on Primo. However, if you're in Primo, you can include these characters and search on them.
> 
> Try searching on "C++" or "C#" as an example. From the home page search box, you'll be taken to Primo results for "C". From there, however, you can perform the original search as expected.

I haven't poked around yet to confirm or solve, just thought I'd report it first.

**Comment by rschwab** [comment]
Confirmed solved by the "Encode Search with encodeURIComponent" commit.

**Comment by Steve-A-Orr** [comment]
Sorry, didn't know I had to close this issue. Thank you.
