### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by rschwab** [quist00/onesearch-local#17]
Sorry for the glut of issues.

The javascript created here comes out to over 6MB. This could represent a pretty significant performance hit.

Is there anyway to trim out some of the dependencies included in the production output?

**Comment by quist00** [comment]
looks like the --prod flag isn't really doing anything.  I wonder if that resulted from "ejecting" it from angular-cli.  There is also a -aot flag that may help, but also doesn't appear to do anything in the projects current form.  I will try creating a new version of the project that is not ejected to see if those flags function as promised.  Web pack should be able to be configured manually to re-enable equivalent functionality, but I don't have the resources to figure out how to do that at this time, so hopefully reverting to out of the box angular-cli will get us where we want to be.

**Comment by quist00** [comment]
Converted back to stock angular-cli in commit 5382d0a59a203d1eaa4ffaea29e1ebd117cfc2dd.
This dropped the dist directory to under 500k. 
Converting back changes the commands used at the command line. See readme.md.
