### ISSUE TITLE
Button to "clear" search box is missing

### ISSUE THREAD

**Issue by Steve-A-Orr** [quist00/onesearch-local#4]
When using the search box in the new Primo UI, a button appears (with an "X" icon) that allows the visitor to "clear" the the query text easily. This functionality would be beneficial on your search box too. 

Do you suppose it would be easy to implement?

**Comment by quist00** [comment]
This would probably not be hard to implement, but I left it off my own implementation on purpose for a couple reasons. I think the clear button's utility is limited on the embedded search box. About the only time I could see it being used is if someone pasted the wrong string in the box, but it would always appear and use up space on mobile screen sizes.  It also changes form at the smallest size and becomes a menu that subsumes advanced search as well, which would be much harder to replicate.

**Comment by Steve-A-Orr** [comment]
I can see your point. I think that we were comparing the Primo version and yours, thinking that if visitors got used to clearing out their search query on Primo then we could benefit from that learned behavior on our _OneSearchLocal_ version. Not a deal-breaker, for sure. Thanks for the discussion...I'll close this issue.
