### ISSUE TITLE
Search box scope/tab drop-down moves page content

### ISSUE THREAD

**Issue by Steve-A-Orr** [quist00/onesearch-local#5]
When using the search box in the new Primo UI, the resulting drop-down window (or modal or whatever you want to call it) which holds the different search tabs/scopes flies or lays over any page content below it on the page. This visual treatment would be beneficial on your search box too, since it currently increases the height of any containing box and pushes content further down the page. (This action might be disorienting to some.)

I'm unsure how one would go about adjusting the z-index of this part of the search display, though. Would you have an idea?

**Comment by quist00** [comment]
I think I tried adding z-index already but failed to set the position correctly.  Will have a look.  Should be a simple fix and I would prefer that behavior as well.

**Comment by Steve-A-Orr** [comment]
You fixed it with commit #8f6bce7. Excellent!!
