### ISSUE TITLE
Search scopes/tab does not disappear when clicking outside of search box

### ISSUE THREAD

**Issue by Steve-A-Orr** [quist00/onesearch-local#7]
I think this is the behavior that we really wanted, when I created the other issue about the "clear" button. As I'm typing in the search box the scopes/tabs are displayed and updated in the fly-out box below--but if I click anywhere else on the page (put focus on a different page component) that fly-out box does not go away.

I suppose that a ```focusout()``` or "on **blur**" event could be used to remove the box, until focus is regained. What do you think?

EDIT: Here are some [blur](https://github.com/angular/angular/issues/7113) [related](https://codedump.io/share/c810eZhed0Eu/1/how-to-use-onblur-event-on-angular2) discussions.

**Comment by quist00** [comment]
this should be resolved; re-open if necessary
