### ISSUE TITLE
App throws enableProdMode() error

### ISSUE THREAD

**Issue by Steve-A-Orr** [quist00/onesearch-local#9]
When looking in my browser console, on my Production instance, I see:
"**Angular is running in the development mode. Call enableProdMode() to enable the production mode.**"

This article seems to describe how to address this (but I don't know how one would include this in the repository code):
http://www.webune.com/forums/angular-is-running-in-the-development-mode-call-enableprodmode-to-enable-the-production-mode.html

**Comment by quist00** [comment]
addressed in 63ba2e08601a0bc7dfae4c06892ce6b6ffd91f58
